// <auto-generated />
using System;
using TodoLists.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TodoLists.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("00000000000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeyondTest.Domain.Entities.TodoItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Title")
                   .HasMaxLength(200)
                   .HasColumnType("nvarchar(200)");

                b.Property<string>("Description")
                   .HasColumnType("nvarchar(max)");

                b.Property<string>("Category")
                   .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsCompleted")
                    .HasColumnType("bit");

                b.Property<DateTime>("Created")
                    .HasColumnType("datetime2");

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("LastModified")
                    .HasColumnType("datetime2");

                b.Property<string>("LastModifiedBy")
                    .HasColumnType("nvarchar(max)");               

                b.HasKey("Id");

                b.ToTable("TodoItems");
            });

            modelBuilder.Entity("BeyondTest.Domain.Entities.Progression", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("TodoItemId")
                   .HasColumnType("int");

                b.Property<DateTime>("Date")
                    .HasColumnType("datetime2");

                b.Property<decimal>("Percent")
                   .HasColumnType("decimal(3,2)");

                b.HasKey("Id");

                b.HasIndex("TodoItemId");

                b.ToTable("Progressions");
            });
#pragma warning restore 612, 618
        }
    }
}
