# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:5001

# GET TodoItems With Pagination
@PageNumber = 1
@PageSize = 10
GET {{Web_HostAddress}}/api/TodoItems/WithPagination?PageNumber={{PageNumber}}&PageSize={{PageSize}}

###

# GET TodoItems
GET {{Web_HostAddress}}/api/TodoItems

###

# POST TodoItems
POST {{Web_HostAddress}}/api/TodoItems
Accept: application/json
Content-Type: application/json

{
  "title": "Title 3",
  "description": "Description",
  "category": "Category"
}

###


# PUT TodoItems
PUT {{Web_HostAddress}}/api/TodoItems/1
Content-Type: application/json

{
  "Id": 1,
  "description": "Description modified"
}

###

# POST Register Progression
POST {{Web_HostAddress}}/api/TodoItems/1/RegisterProgression
Content-Type: application/json

{
  "todoItemId": 1,
  "date": "04/21/2025 1:02:26"
  "percent": 1
}

###

# DELETE TodoItem
DELETE {{Web_HostAddress}}/api/TodoItems/1

###